### ISSUE TITLE
Using an AudioSource located on a separate GameObject?

### ISSUE THREAD

**Issue by lehtiniemi** [hecomi/uLipSync#1]
Is there a way to use an external AudioSource located on another GameObject? In other words, can I point uLipSync which AudioSource to use (not on the same object)?

**Comment by hecomi** [comment]
Thanks for your comment, there is no way to do this now, but it can be done by providing a proxy script. I will try to add it in the next version.

**Comment by hecomi** [comment]
I added `uLipSyncAudioSource` to give the audio data to `uLipSync`. Please see the `01-uLipSync-AudioSource-Proxy` scene in the latest commit.

**Comment by lehtiniemi** [comment]
Wow, thank you so much! :)
