### ISSUE TITLE
Details about MFCC computation required

### ISSUE THREAD

**Issue by Khubaib96** [hecomi/uLipSync#20]
Hi, 

I am a signal processing engineer and could you provide me details of the following things:

1.  Sampling rate (I read that you are downsampling it to 16KHz)
2.  For real-time what is the length of data or audio chunk that you use to extract MFCC and whats the overlapping size?

Regards,
Khubaib

**Comment by hecomi** [comment]
The sampling rate will be a different value depending on the environment (`AudioSettings.outputSampleRate`). Downsampling and the length of data (sample data per frame) will vary depending on the `Profile` setting. So also the overlapping size varies according to it.
<img width="1624" alt="Screen Shot 2022-06-02 at 23 41 57" src="https://user-images.githubusercontent.com/493433/171656546-724efce9-06f3-4062-a014-a590f9dbd5c3.png">
.

**Comment by Khubaib96** [comment]
Hi,

Thank you for the details. Lets assume my audio is of following specifications:

1. Sampling rate 48000
2. Bit depth = 16 bit (short)
3. My audio packets or chunks for real time communication and processing = 1920 shorts or 40ms of data @ 48KHz

I already read the code and there are pre defined calibrated mfcc's.  

My question is if we use the default sampling rate, default bit depth then what is the default size of chunks of audio data from which you extract the mfcc's  ? Based on screen shot, is sample count is the size of audio chunk you use to extract mfcc's..?

**Comment by hecomi** [comment]
Sorry, if you are currently having problems using uLipSync, please let me know and I may be able to explain in more detail.

If 512 samples of 48000 Hz data are processed without downsampling, roughly 10 ms of data will be processed. If the game is running at 60 fps, each frame is approximately 16 ms long, so there is no overlap. At the default target sampling rate of 16000 Hz, 512 samples are 32 ms, so there is roughly 16 ms of overlapping data.

**Comment by Khubaib96** [comment]
I want to integrate the lipsync technique in my learning project in which I am processing audio at 48000Hz with a sample bit depth of 16 bits (short) and packet size is approximately 40ms i.e 1920 shorts. 
I studied your technique and I want to use it in my project just the mfcc technique where you extract mfcc's from audio and then find the hamming distance between the calibrated mfcc's and extracted mfcc's.
Now when I try to extract MFCCs from audio chunks, I need to put some data let's say 40ms of audio data, and then I need to provide an overlapping window to it.
So at this point, I am a bit stuck that how much audio chunk size should I use and how much overlapping should I use to replicate your work.
Hope I am not making it to much difficult to understand.
