### ISSUE TITLE
Followed setup instructions, got namespace missing errors.

### ISSUE THREAD

**Issue by Chris-Creates** [hecomi/uLipSync#29]
Trying to set this up for a job. I followed the installation instructions, and it gave me missing namespace errors, all related to "VRM". I tried the first set up instruction after that, which says if I used UPM, the unity package manager (which I did), to also import Samples / 00. Common Sample. So I imported 00. Common under Samples in the uLipSync package. But that only added more errors about assembly names already existing. I also don't see any option to remove 00. Common, only reimport.

Here's the errors: [https://postimg.cc/0KJmKpd2](https://postimg.cc/0KJmKpd2)

**Comment by hecomi** [comment]
It is not clear from the screenshot, but it appears that you are importing `04. VRM`. If you do not use VRM, then delete this directory. If you want to use it, please import UniVRM.
- https://github.com/vrm-c/UniVRM

**Comment by andy380743909** [comment]
hi @Chris-Creates , you can install all the four packages:


UPM package | git URL
-- | --
com.vrmc.vrmshaders | https://github.com/vrm-c/UniVRM.git?path=/Assets/VRMShaders#v0.108.0
com.vrmc.gltf | https://github.com/vrm-c/UniVRM.git?path=/Assets/UniGLTF#v0.108.0
com.vrmc.univrm | https://github.com/vrm-c/UniVRM.git?path=/Assets/VRM#v0.108.0
com.vrmc.vrm | https://github.com/vrm-c/UniVRM.git?path=/Assets/VRM10#v0.108.0

Then the dependency of VRM will be satisfied.  The last two packages(com.vrmc.univrm, com.vrmc.vrm) are just two different version of vrm, actually you just install the one you need depending on which version of the vrm model you used. If you dont know which version, you can install them all. for more details, please read https://github.com/vrm-c/UniVRM

**Comment by hecomi** [comment]
In the current version of uLipSync, it no longer produces errors even when the VRM package is not included.
