### ISSUE TITLE
VRM SetUp failing

### ISSUE THREAD

**Issue by CarlosPolygonalMind** [hecomi/uLipSync#31]
Hii, I just installed uniVRM and uLipSync but im getting errors with missing namespaces UniVRM10 and Vrm10Instance
![image](https://user-images.githubusercontent.com/98880594/214041232-ac713189-62e6-43ab-9621-ac337a6a1b7f.png)

Don't know how to get it working, tryed different import ways to add the packages but i get the same errors.

**Comment by hecomi** [comment]
Sorry for the late reply. I suspect you're using the old version of VRM (VRM 0.x, `com.vrmc.univrm`), which doesn't include Expression, one of the latest features. This should be automatically disabled by the version definition function of asmdef, but something may be wrong. I'll investigate this later, but in the meantime please remove the `uLipSyncExpressionVRM.cs` and the related Editor Extension file or use the latest version of VRM (VRM 1.0, `com.vrmc.vrm`).

**Comment by RumbleballTheReal** [comment]
Also having issues with the VRM. First of I'm not seeting that dependency mentioned in the install section of the Readme.

I installed VRM 1.0 via the unity package from here: https://github.com/vrm-c/UniVRM/releases/tag/v0.109.0

![image](https://user-images.githubusercontent.com/41473331/225032978-e8c5a8bb-0792-4d09-8dc7-ddf6732f11a4.png)

**Comment by Ozawakun97** [comment]
You should extract both the packages  VRM 1.0 and 0.x VRMBlendshapeproxy is in 0.x version of package

**Comment by hecomi** [comment]
I apologize for the inconvenience caused. In the current version of uLipSync, it no longer produces errors even when the VRM package is not included.
