### ISSUE TITLE
The first parameter set in uLipSyncAnimator does not work.

### ISSUE THREAD

**Issue by Muta-K** [hecomi/uLipSync#37]
uLipSyncAnimatorで一番最初にセットしたパラメータが動作しないようです。

原因を調査すると、`uLipSyncAnimatorEditor`でセットする`uLipSyncAnimator.AnimatorInfo.index`が-1になっており、
`uLipSyncAnimator.OnApplyAnimator`内のif文で弾かれてしまうようです。

解決策としては、`uLipSyncAnimatorEditor.DrawParameterListItem`内の157行目から始まるindex関連の処理で、
±１している操作を修正すれば解決できますが、
これをしてしまうと、既存のユーザーがアップデート時に不具合が出てしまう恐れがありそうです。

何か解決方法、もしくは修正をお願いできないでしょうか？

![image](https://user-images.githubusercontent.com/71075799/231911398-107ac33e-762a-4d0d-ba1d-36580e89f7ca.png)

**Comment by hecomi** [comment]
ご報告ありがとうございます。バグっていますね。。

次回リリースで `Profile` の仕様変更に関係してメジャーバージョンを上げる予定をしておりまして、そのときに併せて破壊的変更として修正いたします。バグ自体はリリースに先立ち、`main` ブランチで更新を行います。

**Comment by hecomi** [comment]
こちらの修正を v3.0.0 に組み込みました：
https://github.com/hecomi/uLipSync/releases/tag/v3.0.0
