### ISSUE TITLE
uLipSyncで口のリップシンクが機能しませんでした

### ISSUE THREAD

**Issue by hide1991** [hecomi/uLipSync#59]
試したこと(Unityバージョン3.16f1)

・新規3DプロジェクトでUniVRM0.108導入(普段VRMモデル表示などで使用していたため)
・Burst・Mathematicsをパッケージマネージャーからインストール
・uLipSync導入し、開発者様の動画を参考に設定したが、口のみが動かなく、音声のみが聞こえる状態に。(uLipSyncの音声データは生成はされます)
※GitHubからZip・スコープ付きレジストリ・Git URLでのuLipSync導入も試しました。

・こちらの方法→https://www.youtube.com/live/4b5fn84RM6E?si=jQhZ5zQusAoUDbcr
　を発見し、uLipSyncの設定を行ったが、同じく口が反応しない
※開発者様のやり方とは違い、タイムラインに音声・生成されたデータ・オブジェクトなどをアタッチしても口パクのみ機能しませんでした。
※生成されたuLipSyncのリップシンクのデータはちゃんと波形や色などは表示されますが、タイムラインに設置しても口が動きませんでした。(男性・女性などのデータに変えましたが、波形や色は生成されてるようです)

・ブレンドシェイプなどの設定も開発者様・上記URLの配信者様のを参考に設定したが、口のみ機能しない(音声は聞こえる)

・uLipSyncパッケージの下部にあったサンプルを導入、VRM0.Xバージョンのサンプルを起動したが、口のみ動かない
・uLipSyncのマイクも試したが、マイク音声が聞こえるのみで、口が動かない。
・短めの文章の音声(VOICEVOXの音声)を試しても、口は動きませんでした。
・VRoidモデルで試しましたが、別のモデルでも同じ現象になりました。

上記の事を3.16バージョンで試しましたがうまく機能できませんでした。
別のバージョンに変えて試してはないのですが、何か解決方法はないでしょうか？

**Comment by hecomi** [comment]
ご質問ありがとうございます。以下の点をご確認いただけないでしょうか？


**1. `uLipSync` の `Profile` の設定及び解析結果**

下のように、何かしらの `Profile` が割り当てられている場合、実行時に *Runtime Information* という場所に解析結果が表示されます。こちらは正常に動作していそうでしょうか？

<img width="701" alt="Screen Shot 2023-12-09 at 18 38 53" src="https://github.com/hecomi/uLipSync/assets/493433/07bf3a22-3089-428b-a6e3-5f2b847431ce">

<img width="701" alt="Screen Shot 2023-12-09 at 18 39 50" src="https://github.com/hecomi/uLipSync/assets/493433/393dd446-6020-49b3-ab46-eff5f1547c0c">



**2. `uLipSyncBlendShapeVRM` の設定** 

VRM 0.X（0.108）をお使いのようですので、VRM モデルに `uLipSyncBlendShapeVRM` をつけることで、`uLipSync` コンポーネントの口パク解析結果を使って VRM のブレンドシェイプを動かし口パクが可能となります。以下のように、お使いのモデルに対してセットアップが完了されているかご確認いただけないでしょうか。

<img width="645" alt="Screen Shot 2023-12-09 at 18 36 40" src="https://github.com/hecomi/uLipSync/assets/493433/7ed60c00-f0a6-4c4f-bd66-4f1e516e9830">

**Comment by hide1991** [comment]
ありがとうございます！

1の解析結果の方は機能してませんでした…！

2の方ですが下記画像のようになってしまいました
![1](https://github.com/hecomi/uLipSync/assets/153356124/2f1476ff-1221-4de4-9977-6ea822b58bf9)

別のバージョンのUniVRMが必要なのでしょうか？

**Comment by hide1991** [comment]
確認し直したところ、解析結果の方は機能したと思われます！
![2](https://github.com/hecomi/uLipSync/assets/153356124/2e8ffa62-e3a4-4dc2-894c-537583f5d98e)

**Comment by hide1991** [comment]
モデルをアタッチし直したところ、このようになりました。
![3](https://github.com/hecomi/uLipSync/assets/153356124/76a06074-0b44-4564-86ec-eaf27055cd0f)

**Comment by hecomi** [comment]
1. に関してですが、Runtime Information の様子を拝見しますとまだオーディオが解析対象として処理されていなそうです。こちら、同じ GameObject に AudioSource がアタッチされているかご確認いただけないでしょうか。

2. 二関してですが

**Comment by hecomi** [comment]
こちらの記事を参考にテストしてみていただけますか？
https://tips.hecomi.com/entry/2023/07/30/191152

**Comment by hide1991** [comment]
ありがとうございます！
こちらの記事には辿り着いてなかったので助かります！
記事・AudioSourceの方、試してみます！

**Comment by hide1991** [comment]
無事リップリンクが機能できました！ありがとうございます！

すみません、疑問なのですが
サンプルの「04-1. VRM 0.X」sceneでは他のモデルでも起動確認できたのですが
新たに作ったsceneで「04-1. VRM 0.X」scene内でのモデルのコンポーネントと全く同じコンポーネントにしても口が動きませんでした…
「04-1. VRM 0.X」scene内でのみの使用なのでしょうか？

**Comment by hide1991** [comment]
お手数おかけしました！
無事にすべて機能できました！ありがとうございます！

**Comment by hecomi** [comment]
無事動いたようで安心いたしました！
ご報告ありがとうございました。
