### ISSUE TITLE
Calculate Phoneme'MFCCs in EditorMode

### ISSUE THREAD

**Issue by lmz244775669** [hecomi/uLipSync#60]
May I ask a question? I have a set of wave file with phoneme file (which contain each phoneme' start time and end time in wave file)，how can i use this set of wave file to calib MFCCs in Profile in EditorMode. I'll appreciate that you can rely, thanks a lot!!!

**Comment by lmz244775669** [comment]
Is there a way like the "public void Bake()" Function In BakedDataEditor that i can use to calib MFCCS in UnityEditorMode with the set of wave file

**Comment by hecomi** [comment]
A tool is available for creating multiple `Profile` instances from WAV files. For more details, please visit:
https://github.com/hecomi/uLipSync?tab=readme-ov-file#batch-conversion-1

If you wish to create `Profile` instances yourself, please refer to the following code:
https://github.com/hecomi/uLipSync/blob/main/Assets/uLipSync/Editor/uLipSyncBakedDataWindow.cs#L106-L112

**Comment by lmz244775669** [comment]
var clip = audioClip;
        float clipDuration = clip.length;
        int bufferSampleNum = clip.samples * clip.channels;
        var buffer = new float[bufferSampleNum];
        var tempBuffer = new float[bufferSampleNum];
        clip.GetData(buffer, 0); 
        var go = new GameObject("uLipSync Baking...");
        var ls = go.AddComponent<uLipSync>();
        ls.OnBakeStart(this);
        // Calib Phonemes in Profile
        for (int i = 0; i < phonemeInfos.Count; i++)
        {
            // startTime - endTime To offestStart - offsetEnd
            double startTime = phonemeInfos[i].startTime;
            double endTime = phonemeInfos[i].endTime;
            string phonemeName = phonemeInfos[i].phonemeName;
            int startOffset = (int)((startTime / clipDuration) * bufferSampleNum);
            int endOffset = (int)((endTime / clipDuration) * bufferSampleNum);
            int durationLength = endOffset - startOffset;
            // srcArray/srcCopyStartIndex/dstArray/dstCopyStartIndex/CopyLength;
            Array.Copy(buffer, startOffset, tempBuffer, 0, durationLength);
            // use lipSync calculate MFCC
            ls.OnBakeUpdate(tempBuffer, clip.channels);
            // use lipSyncCalculated'MFCC copy to Phoneme'MFCC in Profile
            int phonemeIndex = GetPhonemeIndexByName(phonemeName);
            UpdateMfcc(phonemeIndex, ls.mfcc, true);
        }
        ls.OnBakeEnd();
        DestroyImmediate(go);

First of all, Thanks for your reply. I‘ve refetred the "Bake" Func and tried to write codes, but I got every phoneme'MFCC Nan by ls.OnBakeUpdate(). How can i fix this case? My codes are above. I'll appreciate that you can reply, thanks a lot!!!

**Comment by lmz244775669** [comment]
By the way, the profile is newed by myself and add phonemes like "A", "B" and etc in it； Every phoneme'MFCC is newd default and I want use the .wav file and phonemeInfo to calib the phonme'MFCC base on BakeMethod() (the main code is above)

**Comment by lmz244775669** [comment]
I've got normal MFCC value by using sampleFrame，I got NAN caused by received'input data setted by 0.
New Code ： 
        var clip = audioClip;
        float clipDuration = clip.length;
        int bufferSampleNum = clip.samples * clip.channels;
        var buffer = new float[bufferSampleNum];
        int samplePerFrame = clip.frequency / 60 * clip.channels;
        var tempBuffer = new float[samplePerFrame];
        clip.GetData(buffer, 0);

        var go = new GameObject("uLipSync Baking...");
        var ls = go.AddComponent<uLipSync>();
        ls.OnBakeStart(this);
        // Calib Phonemes in Profile
        for (int i = 0; i < phonemeInfos.Count; i++)
        {
            // startTime - endTime To offestStart - offsetEnd
            string phonemeName = phonemeInfos[i].phonemeName;
            Debug.Log(phonemeName);
            double startTime = phonemeInfos[i].startTime;
            double endTime = phonemeInfos[i].endTime;
            int startOffset = (int)Mathf.Floor((float)startTime / clipDuration * bufferSampleNum);
            startOffset = startOffset < 0 ? 0 : startOffset;
            int endOffset = (int)Mathf.Floor((float)endTime / clipDuration * bufferSampleNum);
            endOffset = endOffset >= bufferSampleNum ? bufferSampleNum - 1 : endOffset;
            int durationLength = endOffset - startOffset;
            if (startOffset >= bufferSampleNum - 1)
            {
                startOffset = bufferSampleNum - 1;
                durationLength = 1;
            }

            for (int offset = startOffset; offset < startOffset + durationLength - samplePerFrame; offset += samplePerFrame)
            {
                Array.Copy(buffer, offset, tempBuffer, 0, samplePerFrame);
                // use lipSync calculate MFCC
                ls.OnBakeUpdate(tempBuffer, clip.channels);
                // use lipSyncCalculated'MFCC copy to Phoneme'MFCC in Profile
                int phonemeIndex = GetPhonemeIndexByName(phonemeName);
                UpdateMfcc(phonemeIndex, ls.mfcc, false);
            }

**Comment by hecomi** [comment]
Considering that the `OnBakeUpdate` code is designed to perform pre-calculations based on the assumption that the `Profile` is already calibrated, it may not be applicable in this case. Also, directly handling the buffer can be challenging, so I recommend using the existing code and executing the following steps at runtime:

1. Split existing WAV files according to vowel markers.
2. Set them to an `AudioSource` for loop playback.
3. Add vowels to the `Profile` (please refer to the code at [UI](https://github.com/hecomi/uLipSync?tab=readme-ov-file#ui)).
4. Call `RequestCalibration` for an appropriate duration (refer to [Calibration at Runtime](https://github.com/hecomi/uLipSync?tab=readme-ov-file#calibration-at-runtime)).
5. Proceed with these steps sequentially.

**Comment by lmz244775669** [comment]
Thanks for your reply! I will try the method you've mentioned. I have noticed that the MFCC'calculation code is similar in "Calibration at Runtime” and "OnBakeUpdate" and we also wish to make a tool for automatically  create a Profile in EditorMode  by artists. So we refer to "OnBakeUpdate" func and want to use .wav and vowel markers to create a Profile.

**Comment by lmz244775669** [comment]
I can recogenize the vowels by the Profile which I've created with my code. Maybe the code can work under your recommend.
