### ISSUE TITLE
Output to Animator (parameters)

### ISSUE THREAD

**Issue by liudger** [hecomi/uLipSync#8]
An option to Read the parameters from the Animator Controller to send the values directly to the animator instead of the blendshapes.

**Comment by liudger** [comment]
Ok I wrote the script (copied a lot from the blendshape script) It's not yet perfect but it works quite well. I'll make a pull request soon. I think it will need some revisions:)

https://user-images.githubusercontent.com/4112111/186653231-c2813fac-12df-40d9-835e-311c28ab4bb3.mov

@hecomi thanks for this awesome tool!

**Comment by liudger** [comment]
Ok I wrote the script (copied a lot from the blendshape script) It's not yet perfect but it works quite well. I'll make a pull request soon. I think it will need some revisions:)

https://user-images.githubusercontent.com/4112111/186653231-c2813fac-12df-40d9-835e-311c28ab4bb3.mov

@hecomi thanks for this awesome tool!

**Comment by liudger** [comment]
note: it doesn't support baking or the other features yet. Only runtime

**Comment by hecomi** [comment]
Merged #24
