### ISSUE TITLE
Why coun't add blendshapes?

### ISSUE THREAD

**Issue by Jason-Chn95** [hecomi/uLipSync#9]
When I click add new blendshape, and change the default phoneme name, the blendshape dropdown show nothing.Can you give me some suggestions?Is it that I don't have a blendshape? How to create the plugin recognition blendshape?

**Comment by Jason-Chn95** [comment]
Resolved, unity version cause.

**Comment by alphaRats** [comment]
In case someone runs into this issue again like I did : unticking "Find from Children" and assigning the Skinned Mesh manually solved the issue in our instance
